### ISSUE TITLE
Console were unable to use `/reloadplugin` commands

### ISSUE THREAD

**Issue by cupang-afk** [qu4ks/SimplePluginReloader#1]
in-game _(with OP permission)_ works, but not in the console

doing `/reloadplugin` from console will give you this

```
[13:23:17 INFO]: Unknown command. Type /help for help.
```

**Comment by egorquaks** [comment]
When you run this command in the console without an argument that specifies the name of the plugin you want to reload, the message "Unknown command. Type "/help" for help." will appear. Just specify the plugin you want to reload as an argument and everything will work.
